/*
API Doc

Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  DocumentApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { OneDocCustom } from "./client-custom";

export class OneDoc extends OneDocCustom {
  readonly document: DocumentApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.document = new DocumentApi(configuration);
  }

}
