/*
API Doc

Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentRenderingBucketRequestAssetsInnerContent } from './document-rendering-bucket-request-assets-inner-content';

/**
 * 
 * @export
 * @interface DocumentRenderingBucketRequestAssetsInner
 */
export interface DocumentRenderingBucketRequestAssetsInner {
    /**
     * Relative path where the asset will be stored in the bucket.
     * @type {string}
     * @memberof DocumentRenderingBucketRequestAssetsInner
     */
    'path'?: string;
    /**
     * 
     * @type {DocumentRenderingBucketRequestAssetsInnerContent}
     * @memberof DocumentRenderingBucketRequestAssetsInner
     */
    'content'?: DocumentRenderingBucketRequestAssetsInnerContent;
}

