/*
API Doc

Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentRenderingBucketResponseSignedUrlsInner
 */
export interface DocumentRenderingBucketResponseSignedUrlsInner {
    /**
     * The relative path of the asset in the bucket.
     * @type {string}
     * @memberof DocumentRenderingBucketResponseSignedUrlsInner
     */
    'path'?: string;
    /**
     * Access token for the signed Url.
     * @type {string}
     * @memberof DocumentRenderingBucketResponseSignedUrlsInner
     */
    'token'?: string;
    /**
     * The signed URL to the bucket for the asset in path.
     * @type {string}
     * @memberof DocumentRenderingBucketResponseSignedUrlsInner
     */
    'signedUrl'?: string;
}

