/*
API Doc

Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentRenderingBucketRequestAssetsInner } from './document-rendering-bucket-request-assets-inner';

/**
 * 
 * @export
 * @interface DocumentRenderingBucketRequest
 */
export interface DocumentRenderingBucketRequest {
    /**
     * Array of assets to generate signed URLs for.
     * @type {Array<DocumentRenderingBucketRequestAssetsInner>}
     * @memberof DocumentRenderingBucketRequest
     */
    'assets'?: Array<DocumentRenderingBucketRequestAssetsInner>;
}

