/*
API Doc

Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DocumentGeneratePdfFromBucketRequest
 */
export interface DocumentGeneratePdfFromBucketRequest {
    /**
     * The title of the PDF, defaults to \"document\".
     * @type {string}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'title'?: string;
    /**
     * The identifier of the bucket.
     * @type {string}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'bucket'?: string;
    /**
     * The password of the bucket.
     * @type {string}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'password'?: string;
    /**
     * The username of the bucket.
     * @type {string}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'username'?: string;
    /**
     * Whether or not to generate a test PDF, defaults to true.
     * @type {boolean}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'test'?: boolean;
    /**
     * Whether or not to save the PDF to the bucket, defaults to false.
     * @type {boolean}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'save'?: boolean;
    /**
     * The expiration time of the PDF in days, default is 1 day.
     * @type {number}
     * @memberof DocumentGeneratePdfFromBucketRequest
     */
    'expiresIn'?: number;
}

