/*
API Doc

Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.

The version of the OpenAPI document: 1.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DocumentRenderingBucketResponseSignedUrlsInner } from './document-rendering-bucket-response-signed-urls-inner';

/**
 * 
 * @export
 * @interface DocumentRenderingBucketResponse
 */
export interface DocumentRenderingBucketResponse {
    /**
     * URL for the upload.
     * @type {string}
     * @memberof DocumentRenderingBucketResponse
     */
    'uploadURL'?: string;
    /**
     * Generated username.
     * @type {string}
     * @memberof DocumentRenderingBucketResponse
     */
    'username'?: string;
    /**
     * Generated password.
     * @type {string}
     * @memberof DocumentRenderingBucketResponse
     */
    'password'?: string;
    /**
     * Identifier of the bucket.
     * @type {string}
     * @memberof DocumentRenderingBucketResponse
     */
    'bucket'?: string;
    /**
     * 
     * @type {Array<DocumentRenderingBucketResponseSignedUrlsInner>}
     * @memberof DocumentRenderingBucketResponse
     */
    'signedUrls'?: Array<DocumentRenderingBucketResponseSignedUrlsInner>;
}

